### PR TITLE
Fix: Enforce global constraints for Numpy and Typing-Extensions (#48, #51)

### LINKED ISSUE #48: Dependency conflicts of typing-extensions
When I Install PYNQ on KR260 and Ubuntu 22.04 according to instructions [here](https://github.com/Xilinx/Kria-PYNQ#2-install-pynq), I got the following error:
```
Installing collected packages: typing_extensions
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.13.2
    Uninstalling typing_extensions-4.13.2:
      Successfully uninstalled typing_extensions-4.13.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
exceptiongroup 1.3.0 requires typing-extensions>=4.6.0; python_version < "3.13", but you have typing-extensions 4.3.0 which is incompatible.
Successfully installed typing_extensions-4.3.0
```
What confuses me is that I have had an existing installation of typing_extensions 4.13.2 which satisfies the dependency requirement, but the installation process downgrade it to a lower version 4.3.0 that violates the version requirement. Don't understand why. So, how to fix it? Thanks.

=== Addition ===
Is there any special reason for pinning `typing-extensions` to 4.3.0 in `pynq/sdbuild/packages/python_packages_jammy/requirements.txt`? If not, can developers of Kria-PYNQ change the dependency to `typing-extensions >= 4.6.0`? Thanks.

### LINKED ISSUE #51: Numpy 2.2.6 Dependency for opencv-python 4.12.0.88
I ran into an issue with the installation of PYNQ on my KR260 yesterday. Despite two fresh installs, I kept having an issue with the allocate() function call error:

`AttributeError: attribute 'device' of 'numpy.ndarray' objects is not writable`

After some help from the google chatbot as well as Mario Ruiz on the pynq forum, I was able to get the proper version of numpy installed. There it gave an error:

```
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4
```

Long story short, I think the current scripts are inadvertently installing the latest version of opencv-python, which requires numpy 2.xx. 

To replicate, follow the instructions in your readme.md file to install pynq. During the install process, you should see the script install and uninstall numpy 2.26 one or two times. Then check for the installed version of numpy and opencv-python. 

Here's a [link to the thread](https://discuss.pynq.io/t/pynq-helloworld-issue-with-allocate-function-call/8612/2) with more info.

### LINKED ISSUE #56: Error during installation
This error is normal during instalation?
------------------------------------------------------------------------------------------------------------------
Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
exceptiongroup 1.3.1 requires typing-extensions>=4.6.0; python_version < "3.13", but you have typing-extensions 4.3.0 which is incompatible.
Successfully installed typing_extensions-4.3.0
------------------------------------------------------------------------------------------------------------------
I did the installation, and I can't run any overlay. I don't know what I did wrong. I use Ubuntu 22.04 LTS and Vivado 2022.2 . Also, the selftest.sh doesn't work, and the pynq-helloworld on Jupiter doesn't work.
I use KRIA KR260. I follow this script
git clone https://github.com/Xilinx/Kria-PYNQ.git
cd Kria-PYNQ/
sudo bash install.sh -b KR260

### PR DESCRIPTION
**Pull request by mosesrotesmeer**
**Summary**
This PR aims to resolve the dependency resolution failures currently affecting the Kria-PYNQ installation process (#48 and #51).

**Changes and Rationale**
While previous efforts (such as #43) successfully identified the numpy version requirement, the sequential nature of this install script allows subsequent pip calls (like opencv-python or pytest) to trigger an upgrade to Numpy 2.0, effectively overriding previous pins.

To ensure environment stability throughout the entire installation lifecycle:

- Centralized Constraints: I have introduced a global PIP_CONSTRAINT manifest. This ensures that every pip command in the script respects the required versions without needing to manually pin every individual install line.

- Numpy Stability (#51): Sets a global requirement for numpy==1.26.4 to maintain compatibility with PYNQ 3.0.1.

- Typing-Extensions Fix (#48): Enforces typing-extensions>=4.6.0 to prevent an automated downgrade that was causing a conflict with exceptiongroup.

- Consolidated Pins: Grouped core PYNQ package versions into the manifest for easier maintenance in the future.

This approach ensures that the environment remains consistent from the first pip call to the last.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -144,15 +144,26 @@ then
         exit 1
 fi
 
-# Numpy 2.0 workaround:
+# =========================================================
+# Global Pip Constraints
+# =========================================================
+cat > /tmp/pynq_3.0.1_constraints.txt <<EOT
+numpy==1.26.4
+typing-extensions>=4.6.0
```
Comment (mariodruiz) [inline install.sh:152]: Thank you for this PR. Why are your constraining this package? I tried the install and this is not respected, 4.15.0 end up being installed.

Comment (mosesrotesmeer) [reply install.sh:152]: Hi Mario, for typing-extensions, 4.6.0 is the minimum version where typing-extensions where introduced and it's a requirement for the package exceptiongroup. It's also described in #48. 
If you have 4.15.0 installed, it was actually respected, since I pinned the **minimum** version to be 4.6.0.

Best, Patrick

Comment (mariodruiz) [reply install.sh:152]: Got it. I missed the '>' that's why I said it is not respected.
Thank you Patrick.

**Review by mariodruiz — APPROVED** [review]

**Comment by mariodruiz** [comment]
@mosesrotesmeer thank you for your contribution.
